@echo off
attrib -s -h *.bat
attrib -s -h Adb
attrib -s -h AppLayout
attrib -s -h Android_Studio_Projects
attrib -s -h APK
attrib -s -h App_source_code
attrib -s -h Apps
attrib -s -h BatchScript
attrib -s -h Code_and_Hack
attrib -s -h Device_recording
attrib -s -h Downloads
attrib -s -h Drawable
attrib -s -h Earn_Money_Online
attrib -s -h Eclipse
attrib -s -h TextFiles
attrib -s -h Hackwares
attrib -s -h IconsArchieve
attrib -s -h iLearn
attrib -s -h ISO
attrib -s -h Jars
attrib -s -h Learning_Mind
attrib -s -h Millionaires's_Sayings
attrib -s -h MSPowerPoint
attrib -s -h Music
attrib -s -h MyApps
attrib -s -h MyProjects
attrib -s -h MySoftwares
attrib -s -h RegeditHacks
attrib -s -h ShortcutsLinks
attrib -s -h SignedAPK
attrib -s -h Software
attrib -s -h SourceCodes
attrib -s -h Splashtop
attrib -s -h St_Xavier's_College
attrib -s -h TheHackerNews
attrib -s -h Tutorials
attrib -s -h Tweaks
attrib -s -h VirtualHDD
attrib -s -h WallPapers
exit